config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments, only: [:edit, :create, :update, :destroy]

  resources :blog_posts

  root 'blog_posts#index'

  get '/:name' => 'blog_posts#user_posts', as: :user_posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

	has_many :comments, dependent: :destroy
	belongs_to :user

	validates :title, :blog_entry, presence: true
	validates :title, uniqueness: true, length: { maximum: 140 }

	paginates_per 3
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blog_post
	belongs_to :user

	validates :comment_entry, :blog_post_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :blog_posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys:[:username, :avatar])
  	devise_parameter_sanitizer.permit(:account_update, keys:[:username, :avatar])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

	before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

	include ApplicationHelper

	def user_posts
		@user = User.find_by(username: params[:name])
	end

	def index
		@blog_posts = BlogPost.all.page(params[:page])
	end

	def show
		@comment = Comment.new
	end

	def edit
		no_access_visitors(current_user, @blog_post)
	end

	def new
		@blog_post = BlogPost.new
	end

	def create
		@blog_post = BlogPost.new(blog_post_params)

		respond_to do |format|
			if @blog_post.save
				format.html { redirect_to blog_post_url(@blog_post), notice: "Blog post successfully created" }
			else
				format.html { render :new }
			end
		end
	end

	def update
		@blog_post = BlogPost.find(params[:id])

		if (@blog_post.update(blog_post_params))
			redirect_to @blog_post, notice: "Blog post successfully updated" 
		else
			render 'edit'
		end
	end

	def destroy
		@blog_post.destroy

		respond_to do |format|
			format.html { redirect_to blog_posts_url, notice: "Blog post successfully deleted"}
		end
	end

	private

	def set_blog_post
		@blog_post = BlogPost.find(params[:id])
	end

	def blog_post_params
		params.require(:blog_post).permit(:title, :blog_entry, :user_id)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:edit, :update, :destroy]

	include ApplicationHelper

	def index
    	@comments = Comment.all
  	end

	def edit
		@blog_post = BlogPost.find(@comment.blog_post_id)
		no_access_visistors(current_user, @comment)
	end

	def show
  	end

	def new
    	@comment = Comment.new
  	end

	def create
		@comment = Comment.new(comment_params)

		respond_to do |format|
			if @comment.save
				format.html { redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Comment successfully created" }
			else
				format.html { redirect_back fallback_location: root_path }
			end
		end
	end

	def update
		respond_to do |format|
			if @comment.update(comment_params)
				format.html { redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Comment successfully updated" }
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		@comment.destroy

		respond_to do |format|
			format.html { redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Comment successfully deleted"}
		end
	end

	private
	def set_comment
		@comment = Comment.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:user_id, :comment_entry, :blog_post_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def no_access_visitors(current_user, post_user)

		unless current_user.id == post_user.user_id
			redirect_to root_url
		end

	end
end

app/helpers/blog_post_helper.rb
module BlogPostHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, local: true) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "Error") %> prohibited this post from being saved:</h2>

      <ul>
      <% blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>

  <div class="form-group hidden">
    <%= f.number_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= f.text_area :blog_entry, rows: 12, placeholder: "Enter Text Here", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div><br>

<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Back', @blog_post, class: "btn btn-info" %> 
<%= link_to 'All Blog Posts', blog_posts_path, class: "btn btn-default" %>

app/views/blog_posts/index.html.erb
<h1>Welcome <%= current_user.username %></h1>

<div class="row">
	<% @blog_posts.each do |blog_post| %>
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<%= link_to blog_post.title, blog_post %>
				</div>
				<div class="panel-body">
					by <em><%= link_to blog_post.user.username, user_posts_path(name: blog_post.user.username) %></em><br>
					<p><i>Created: <%= blog_post.created_at.strftime("%m/%d/%Y at %I:%M%p") %></i></p>
					<p><%= blog_post.blog_entry[0..150].html_safe %>..<%= link_to "Read More", blog_post_path(blog_post) %></p>
				</div>
				<div class="panel-footer">
					<% if current_user.id == blog_post.user_id %>
						<%= link_to "Edit", edit_blog_post_path(blog_post), class: "btn btn-warning" %> 
						<%= link_to "Destroy", blog_post_path(blog_post), method: :delete, data: { confirm: "Are you sure you want to delete?"}, class: "btn btn-danger" %>
					<% end %>
				</div>
			</div>
		</div>
	<% end %>
</div>

<%= paginate @blog_posts %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<br>

<%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default" %>

app/views/blog_posts/show.html.erb
<div class="panel panel-primary">
	
	<div class="panel-heading">
		<%= @blog_post.title %>
	</div>

	<div class="panel-body">
		<p><%= @blog_post.user.username %></p>
		<p><%= time_ago_in_words(@blog_post.created_at) %></p>
		<p><%= @blog_post.blog_entry.html_safe %></p>
	</div>

	<div class="panel-footer">
		<% if current_user.id == @blog_post.user_id %>
			<%= link_to "Edit", edit_blog_post_path(@blog_post), class: "btn btn-warning" %>
		<% end %>
	</div>

</div>

<div class="panel panel-success">
	
	<div class="panel-heading">
		Make A Comment
	</div>

	<div class="panel-body">
		<%= render 'comments/form' %>
	</div>

</div>

<div class="panel panel-default">
	
	<div class="panel-heading">
		All comments
	</div>

	<div class="panel-body">
		<%= render 'comments/comment' %>
	</div>

</div>

app/views/blog_posts/user_posts.html.erb
<h1>All Posts by <b><%= @user.username %></b></h1>

<% @user.blog_posts.each do |blog_post| %>
	<div class="row">
		<div class="col-md-12">
			<div class="well">
				<h3><%= link_to blog_post.title, blog_post %></h3>
				<p><em>posted on <%= blog_post.created_at.strftime("%m/%d/%Y at %I:%M%p") %></em></p>
				<p><%= blog_post.blog_entry.html_safe %></p>
				<p>
					<%= link_to "Show", blog_post, class: "btn btn-info" %> 
					<% if current_user.id == blog_post.user_id %>
						<%= link_to "Edit", edit_blog_post_path(blog_post), class: "btn btn-warning" %> 
						<%= link_to "Destroy", blog_post_path(blog_post), method: :delete, data: { confirm: "Are you sure you want to delete?"}, class: "btn btn-danger" %>
					<% end %>
				</p>
			</div>
		</div>
	</div>
<% end %>

app/views/comments/_comment.html.erb
<% @blog_post.comments.each do |comment| %>

	<h4><%= link_to comment.user.username, user_posts_path(name: comment.user.username) %></h4>
	<p><%= time_ago_in_words(comment.created_at) %></p>
	<p><%= comment.comment_entry %></p>

	<% if current_user.id == comment.user_id %>

		<%= link_to "Edit", edit_comment_path(comment), class: "btn btn-warning" %> 
		<%= link_to "Destroy", comment_path(comment), method: :delete, data: { confirm: "Are you sure you want to delete?"}, class: "btn btn-danger" %>


	<% end %>

<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>
	
	<% if @comment.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@comment.errors.count, "Error") %> prohibited this from being saved.</h2>

			<ul>
				<% @comment.errors.full_messages.each do |message|%>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group hidden">
		<%= f.number_field :user_id, value: current_user.id %>
	</div>

	<div class="form-group">
		<%= f.text_area :comment_entry, rows: 4, class: "form-control", placeholder: "Comment Here" %>
	</div>

	<div class="form-group hidden">
		<%= f.number_field :blog_post_id, value: @blog_post_id %>
	</div>

	<div class="actions">
		<%= f.submit "Post Comment", class: "btn btn-primary" %>
	</div>

<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

<br>

<%= link_to "Back", blog_post_path(@comment.blog_post_id), class: "btn btn-info" %> 

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "All Blog Posts", blog_posts_path, class: "navbar-brand" %></li>
          <li><%= link_to "New Blog Post", new_blog_post_path %></li>
        </ul>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li ckass "dropwdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= gravatar_tag current_user.email, size: 20 %> <%= current_user.username %> <span class ="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
         </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alec Yates' Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

  	<div class="container">
	    <%= yield %>
    </div>
  </body>
</html>